### ISSUE TITLE
fmt format error

### ISSUE THREAD

**Issue by empty-spacebar** [versatran01/dsol#10]
The complete error log is shown below：

/home/XXXXXXXX/catkin/catkin_dsol/src/dsol-main/sv/dsol/frame.cpp:21:37:   required from here
/usr/local/include/fmt/core.h:1017:9: error: static assertion failed: Cannot format argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#formatting-user-defined-types
 1017 |         formattable,
      |         ^~~~~~~~~~~
make[2]: *** [dsol-main/sv/dsol/CMakeFiles/sv_dsol_frame.dir/build.make:63: dsol-main/sv/dsol/CMakeFiles/sv_dsol_frame.dir/frame.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2367: dsol-main/sv/dsol/CMakeFiles/sv_dsol_frame.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

It seems that there are some variables requiring being type conversion. Unfortunately, fmt coding is not what i familiar with.

By the way, could you please tell me which fmt and abseil version do you use? I also find several Version compatibility Issues about them.

Thanks anyway.

**Comment by versatran01** [comment]
Here see this.
https://github.com/versatran01/dsol/blob/main/.github/workflows/build.yaml

**Comment by empty-spacebar** [comment]
It works, thanks bro!
