### ISSUE TITLE
cannot run dsol

### ISSUE THREAD

**Issue by cpymaple** [versatran01/dsol#11]
Hi, when I run DSOL based on Ubuntu 20.04 Ros Noetic, I encounter the below problem. Do you know how to solve it? Thanks for your time~

ROS_MASTER_URI=http://localhost:11311

process[dsol_data-1]: started with pid [284373]
WARNING: Logging before InitGoogleLogging() is written to STDERR
W20230125 18:18:55.030283 284373 dataset.cpp:734] Could not infer dataset name from dir '/home/cpy/Datasets/dataset/sequences/00'
[ERROR] [1674641935.030472459]: Invalid dataset at: /home/cpy/Datasets/dataset/sequences/00
[dsol_data-1] process has died [pid 284373, exit code -11, cmd /home/cpy/catkin_ws_DSOL/devel/lib/dsol/sv_dsol_node_data __name:=dsol_data __log:=/home/cpy/.ros/log/63cd045a-9c94-11ed-80d5-fd604bd6d0fd/dsol_data-1.log].
log file: /home/cpy/.ros/log/63cd045a-9c94-11ed-80d5-fd604bd6d0fd/dsol_data-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by versatran01** [comment]
This was my bad. You need to put the kitti dataset under a folder named kitti
