### ISSUE TITLE
photometric error jacobian w.r.t host frame idepth

### ISSUE THREAD

**Issue by Roger-Chuh** [versatran01/dsol#12]
hi, thank you for open sourcing your excellent work. i am derivating the jacobians used in pba, and having problems about the term: "Vector3d dp1_dq0 = T10_fej.translation(); " , in function AdjustCost::CalcJacGeo( ) of adjust.cpp, , according to my derivation, this term is something like "dp1_dq0 = -T10_fej.linear()*point0.pt()/q0", when i run my modification, the optimization won't converge. may i ask for some detailed derivetions about this term? thanks a lot.

**Comment by versatran01** [comment]
The p1 in there is actually p1'. 
You can see in L468 and L469. 
This is needed to avoid dividing by 0 (if q0 is 0).

**Comment by Roger-Chuh** [comment]
thank you for your immediate reply. i should've deriveted the jacobians with L469 instead of L468, lesson learned.
