### ISSUE TITLE
affine-related poor running result

### ISSUE THREAD

**Issue by empty-spacebar** [versatran01/dsol#13]
Everything is incredible with the original config file, no mather precision or CPU-cost.

BUT when turn on the affine option in config file, the trajectory just crash immediately.

Is there anything i neglect to change along with affine?

![image](https://user-images.githubusercontent.com/51714175/217456827-dfea7d2f-9bc1-4a9e-9a8c-4839c71ae457.png)

As the image shown above, the direction is from rightBottom to leftTop, the green line means groud_ture and red means the error trajectory.

As for the terminal output, "kf=true" appear in every frame, and the point tracking fails in every frame.

**Comment by Roger-Chuh** [comment]
[  Hjj.block<dp, da>(ia1, 0).noalias() += G1.transpose() * ph.ItA1;](https://github.com/versatran01/dsol/blob/009445f98ad09a47370609efa6614a39453a54b9/sv/dsol/hessian.cpp#L245)
try change this line to "Hjj.block<dp, da>(0, ia1).noalias() += G1.transpose() * ph.ItA1;", guess it's a typo

**Comment by versatran01** [comment]
Does changing this line fix the poor result?

**Comment by Roger-Chuh** [comment]
in my case, yes.

**Comment by empty-spacebar** [comment]
> [ Hjj.block<dp, da>(ia1, 0).noalias() += G1.transpose() * ph.ItA1;](https://github.com/versatran01/dsol/blob/009445f98ad09a47370609efa6614a39453a54b9/sv/dsol/hessian.cpp#L245) try change this line to "Hjj.block<dp, da>(0, ia1).noalias() += G1.transpose() * ph.ItA1;", guess it's a typo

It works! And the performance exceeds every result i got before. Thanks bro!

**Comment by Roger-Chuh** [comment]
> > [ Hjj.block<dp, da>(ia1, 0).noalias() += G1.transpose() * ph.ItA1;](https://github.com/versatran01/dsol/blob/009445f98ad09a47370609efa6614a39453a54b9/sv/dsol/hessian.cpp#L245) try change this line to "Hjj.block<dp, da>(0, ia1).noalias() += G1.transpose() * ph.ItA1;", guess it's a typo
> 
> It works! And the performance exceeds every result i got before. Thanks bro!

don't mention it

**Comment by versatran01** [comment]
Feel free to make a PR. Otherwise I will just change it. Thanks!

**Comment by empty-spacebar** [comment]
> Feel free to make a PR. Otherwise I will just change it. Thanks!

About PR, you mean photometric calibration? I have some question about it, check your gmail please if you're available.

**Comment by Roger-Chuh** [comment]
> Feel free to make a PR. Otherwise I will just change it. Thanks!

you might just go ahead and change it :D

**Comment by empty-spacebar** [comment]
> > > [ Hjj.block<dp, da>(ia1, 0).noalias() += G1.transpose() * ph.ItA1;](https://github.com/versatran01/dsol/blob/009445f98ad09a47370609efa6614a39453a54b9/sv/dsol/hessian.cpp#L245) try change this line to "Hjj.block<dp, da>(0, ia1).noalias() += G1.transpose() * ph.ItA1;", guess it's a typo
> > 
> > 
> > It works! And the performance exceeds every result i got before. Thanks bro!
> 
> don't mention it

By the way, RU chinese? Here's my wechat(13632049653).I hope we can communicate further.Any other social media is OK.
