### ISSUE TITLE
Catkin_make fail with absl and hash problem

### ISSUE THREAD

**Issue by konszy** [versatran01/dsol#16]
catkin_make failed with sophus, fmt, absl problem, need to check the version of them. THANKS!

**Comment by konszy** [comment]
The error seems form absl? Any idea to fix that?
<img width="756" alt="截屏2023-04-20 11 48 53" src="https://user-images.githubusercontent.com/34244243/233253490-aa704c50-e07e-420b-8c86-f8dbdc0b1dc2.png">
<img width="756" alt="截屏2023-04-20 11 49 23" src="https://user-images.githubusercontent.com/34244243/233253499-238ba687-d7e2-42b9-aca5-1b9ed3966b3f.png">
<img width="751" alt="截屏2023-04-20 11 50 51" src="https://user-images.githubusercontent.com/34244243/233253708-077748d4-1c66-4cd8-8075-446d223d3b27.png">

**Comment by versatran01** [comment]
I'm using 20220623, which is the one installed via `mamba install abseil-cpp`

**Comment by konszy** [comment]
> I'm using 20220623, which is the one installed via `mamba install abseil-cpp`
> 
> You can also look here https://github.com/versatran01/dsol/blob/main/.github/workflows/build.yaml
> 
> I also just pushed a fix to make it compile with fmt v9.

Thanks for updating. I still got same problem(same warning), after I followed the command in build.yaml, and rebuild it. 
Any idea why this error happens? Always stuck with summary.cpp, which uses flat_hash_map.h.

**Comment by versatran01** [comment]
I have no idea why this happens based on your screenshot.

**Comment by konszy** [comment]
Problem solved. If the error shows "undefined reference to absl::lts_xxxxxxx", try rm all absl stuff and re cmake with"-DABSL_PROPAGATE_CXX_STD", it should works.
