### ISSUE TITLE
Questions about PBA jacobian

### ISSUE THREAD

**Issue by NUAAguo** [versatran01/dsol#8]
Hi, i'm very confusing about pba jacobian.
I thought that PBA use additive approach, not inverse compositional, the error function is I1(W(x0;T^w_1,T^w_0,q0)) - I0(x0). So i direct calculate partial err/ partial T^w_1 and partial err/partial T^w_0. But it's diff from  CalcJacGeo function. 
hope for your response!

**Comment by versatran01** [comment]
Yes, PBA does not use inverse compositional algorithm.

**Comment by NUAAguo** [comment]
thanks!
CalcJacGeo func in adjust.cpp
p1' = R10 * n0      + t10 * q0;     R10 = R^w_1.inv * R^w_0;     t10 = R^w_1.inv * (t^w_0 - t^w_1)
when i calculate the jacobian of warp function to T^w_1 and T^w_0, the jacobian to R^w_1 and R^w_0 is same as the code;
but diff when i calculate dp1_dt1 and dp1_dt0
i thought that dp1_dt1 = partial t10*q0 / partial t^w_1 = -R^w_1.inv *q0
                      dp1_dt0 = R^w_1.inv *q0
but in code, dp1_dt1 = -q0* identity
                    dp1_dt0 = R10*q0

**Comment by versatran01** [comment]
The function is not computing jacobian wrt t^w_1, but wrt delta t^w_1, which is the error state.

**Comment by NUAAguo** [comment]
i don't understand this error state, does it means the error function is: I1(W(x,T^w_1,T^w_0,dT^w_1,dT^w_0,q0))-I0(x)?
so the T10 = (T^w_1* dT^w_1).inv * (T^w_0*dT^w_0)
then i need to compute jacobian of warp to dT?

**Comment by versatran01** [comment]
Yes

**Comment by NUAAguo** [comment]
Thank u so much! i got the same as code.

**Comment by NUAAguo** [comment]
But still i have a question : why not compute jacobian to T^w_1 T^w_0 directly, instead compute jacobian to delta

**Comment by versatran01** [comment]
Because that's how linear least squares works: you linearize at some nominal state x_0 using first order Taylor approximation, f(x) = f(x_0) + f'(x_0) dx. Therefore, the quantity you solve for is dx, which is the error/delta state.

**Comment by NUAAguo** [comment]
Oh, i see. now i understand. thanks a lot! By the way, the code is beautiful!

**Comment by CNchence** [comment]
Thanks for your open source, why not use inverse compositional algorithm in PBA? It's a lot fast.

**Comment by versatran01** [comment]
Because inverse depth is a variable to be optimized. If I use inverse compositional, then the jacobian wrt inverse depth is zero.
